### ISSUE TITLE
Erro de charset

### ISSUE THREAD

**Issue by caiocvsilva** [MPMG-DCC-UFMG/C01#722]
## Comportamento Esperado
Salvar a página como um html sem erros.

## Comportamento Atual
Ao tentar coletar a página principal da prefeitura de Betim, o coletor falha com o seguinte erro:
```
  File "/home/caio/.local/lib/python3.9/site-packages/scrapy_puppeteer/middlewares.py", line 216, in _process_request
    encoding = params['charset']
KeyError: 'charset' 
```

## Passos para reproduzir o erro

  1. Coletor estático da página 'http://www.betim.mg.gov.br/home/41822%3B66975%3B03%3B0%3B0.asp'
  2. Nenhum passo dinâmico ou configurarão avançada é necessária

## Especificações da Coleta

  - Fonte: http://www.betim.mg.gov.br/home/41822%3B66975%3B03%3B0%3B0.asp

**Comment by aluiza22** [comment]
Também estou tendo esse problema na #685 utilizando apenas o coletor estático:
`File "/home/ana/C01/crawlers/base_spider.py", line 220, in store_html
    encoding = params['charset']
KeyError: 'charset'`

Depois tentei usar passos dinâmicos para ter uma espera de 10s e salvar a página, mas o seguinte erro apareceu:
`File "/home/ana/C01/venv2/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 237, in _rewriteError
raise type(error)(msg)
pyppeteer.errors.NetworkError: Execution context was destroyed, most likely because of a navigation.`

**Comment by caiocvsilva** [comment]
Este erro está relacionado a opção "Método de detecção de codificação das páginas*" que se encontra na página de criação de um coletor, sob detalhes de coletor → explorar links → opções avançadas. Com o método padrão 'Via cabeçalho da resposta ", o erro de charset acontece, possivelmente por uma resposta incorreta do servidor. Ao alterar para o modo "Automático", o problema é resolvido.
